import { apiFetch } from "@/lib/api";

export type TaskListItem = {
  id: string;
  userId: string;
  gameId: string;
  taskTypeId: string;
  templateId?: string | null;
  sourceType:
    | "MANUAL"
    | "TEMPLATE_GENERATED"
    | "DAILY_PLAN"
    | "PLANNER_GENERATED";
  title: string;
  description?: string | null;
  status:
    | "PENDING"
    | "SCHEDULED"
    | "DONE"
    | "SKIPPED"
    | "EXPIRED"
    | "CANCELLED";
  priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  scheduledDate?: string | null;
  dueDate?: string | null;
  expiresAt?: string | null;
  completedAt?: string | null;
  isAllDay: boolean;
  isAutoGenerated: boolean;
  requiresAttention: boolean;
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
  game: {
    id: string;
    name: string;
    slug: string;
  };
  taskType: {
    id: string;
    key: string;
    label: string;
  };
};

export type TaskView = "all" | "scheduled" | "pending";

export type CreateTaskPayload = {
  gameId: string;
  taskTypeId: string;
  templateId?: string;
  sourceType:
    | "MANUAL"
    | "TEMPLATE_GENERATED"
    | "DAILY_PLAN"
    | "PLANNER_GENERATED";
  title: string;
  description?: string;
  status?:
    | "PENDING"
    | "SCHEDULED"
    | "DONE"
    | "SKIPPED"
    | "EXPIRED"
    | "CANCELLED";
  priority?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  scheduledDate?: string;
  dueDate?: string;
  expiresAt?: string;
  completedAt?: string;
  isAllDay?: boolean;
  isAutoGenerated?: boolean;
  requiresAttention?: boolean;
  notes?: string;
};

export type UpdateTaskPayload = {
  gameId?: string;
  taskTypeId?: string;
  title?: string;
  description?: string;
  status?:
    | "PENDING"
    | "SCHEDULED"
    | "DONE"
    | "SKIPPED"
    | "EXPIRED"
    | "CANCELLED";
  priority?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  dueDate?: string;
  expiresAt?: string;
  isAllDay?: boolean;
  requiresAttention?: boolean;
  notes?: string;
};

export function getTasksRequest(view: TaskView = "all") {
  return apiFetch<TaskListItem[]>(`/tasks?view=${view}`);
}

export function createTaskRequest(payload: CreateTaskPayload) {
  return apiFetch<TaskListItem>("/tasks", {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

export function updateTaskRequest(taskId: string, payload: UpdateTaskPayload) {
  return apiFetch<TaskListItem>(`/tasks/${taskId}`, {
    method: "PATCH",
    body: JSON.stringify(payload),
  });
}

export function scheduleTaskRequest(taskId: string, scheduledDate: string) {
  return apiFetch<TaskListItem>(`/tasks/${taskId}/schedule`, {
    method: "PATCH",
    body: JSON.stringify({ scheduledDate }),
  });
}

export function unscheduleTaskRequest(taskId: string) {
  return apiFetch<TaskListItem>(`/tasks/${taskId}/unschedule`, {
    method: "PATCH",
  });
}

export function markTaskDoneRequest(taskId: string, completedAt?: string) {
  return apiFetch<TaskListItem>(`/tasks/${taskId}/done`, {
    method: "PATCH",
    body: JSON.stringify(completedAt ? { completedAt } : {}),
  });
}

export function deleteTaskRequest(taskId: string) {
  return apiFetch<{ success: boolean }>(`/tasks/${taskId}`, {
    method: "DELETE",
  });
}
